(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(require 'init-package)
(require 'init-editor)
(require 'init-ivy)
(require 'init-ibuffer)
(require 'init-git)
(require 'init-mail)
(require 'init-rss)
(require 'init-misc)
(require 'init-shell)
(require 'init-lisp)
(require 'init-clang)
(require 'init-golang)
