(setq user-full-name "c4droid")
(setq user-mail-address "c4droid@foxmail.com")
(require 'gnus)
(require 'smtpmail)
(require 'message)
(require 'mail-source)
(setq send-mail-function 'smtpmail-send-it)
(setq message-send-mail-function 'smtpmail-send-it)
(setq smtpmail-smtp-server "smtp.qq.com")
(setq smtpmail-default-smtp-server "smtp.qq.com")
(setq gnus-select-method '(nntp "news.newsfan.net"))
(setq gnus-secondary-select-methods '((nnimap "imap.qq.com")))
(setq mail-sources '((imap :server "imap.qq.com"
			   :user "1729831470@qq.com")))
(provide 'init-mail)
