(require 'package)
(setq package-archives '(("gnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
			 ("melpa" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
			 ("org" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/org/")))
(setq package-enable-at-startup nil)
(package-initialize)
(unless (not package-archive-contents)
  (package-refresh-contents))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file t)
(provide 'init-package)
