(require 'epa)
(setq epa-pinentry-mode 'loopback)
(setq epa-file-select-keys 0)
(setq epa-file-cache-passphrase-for-symmetric-encryption t)
(epa-file-enable)
(defun c4droid/kill-gpg-agent ()
  (shell-command "pkill gpg-agent"))
(add-hook 'kill-emacs-hook 'c4droid/kill-gpg-agent)
(provide 'init-misc)
